#profile 설정
spring:
    config:
        activate:
            on-profile: dev

#테스트 프로파일
---
spring:
    profiles:
        active: test
    sql:
        init:
            mode: never
    datasource:
        url: jdbc:h2:tcp://localhost/~/test
        driver-class-name: org.h2.Driver
        username: sa
        password:
        h2:
            console:
                enabled: true
                path: /h2-console
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true

#개발 프로파일
---
spring:
    datasource:
        url: jdbc:sqlite:db.sqlite
        driver-class-name: org.sqlite.JDBC
        initialization-mode: always
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        database-platform: org.hibernate.community.dialect.SQLiteDialect
    sql:
        init:
            mode: always

